### ISSUE TITLE
Update Rails version from 7.0.0 to 7.1.0

### ISSUE THREAD

**Issue by otegami** [ranguba/ranguba#34]
## What we will do

- [x] Search for what we should do for updating
- [x] Update patch version (7.0.8 at this moment)
- [x] Update gems
- [x] Update Rails version to 7.1.0
- [x] Configure new Rails default settings one by one
- [ ] Update load defaults to v7.1
 
ref: https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#upgrading-from-rails-7-0-to-rails-7-1

**Comment by otegami** [comment]
> Search for what we should do for updating

Patch バージョンを上げる際に気をつけないことを確認する。

**Comment by otegami** [comment]
リリースノートベースで確認してみたが破壊的な変更は入っていないので問題なさそう。
- [v7.0.1](https://github.com/rails/rails/releases/tag/v7.0.1) ~ [v7.0.8](https://github.com/rails/rails/releases/tag/v7.0.1)

**Comment by otegami** [comment]
下記の非互換な対応が入っているが、Ranguba では利用していないので問題なさそう。
- has_one
- enum

https://scrapbox.io/ruby-jp/rails_v7.0.5,_v7.0.6_%E9%9D%9E%E4%BA%92%E6%8F%9B%E5%A4%89%E6%9B%B4%E3%81%BE%E3%81%A8%E3%82%81%E3%83%A1%E3%83%A2#64748797ffe48d001c967a89

**Comment by otegami** [comment]
パッチバージョンであり、大きな問題もなさそうなので v7.0.8 まで上げてみる。

**Comment by otegami** [comment]
Gemfile 内で、下記で指定されているのですでにパッチバージョンは上がりきった v7.0.8 になっている。
```
gem "rails", "~> 7.0.0"
```

**Comment by otegami** [comment]
>  Update gems

**Comment by otegami** [comment]
> Update Rails version to 7.1.0

Rails 7.1 で対応が必要そうなことの確認をした。
- https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#upgrading-from-rails-7-0-to-rails-7-1

テスト時のエラーハンドリングが少し変わっていそうだが、特に大きな影響はなさそう。
- アップグレードする際にもう少し確認する。
- https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#new-ways-to-handle-exceptions-in-controller-tests-integration-tests-and-system-tests

**Comment by otegami** [comment]
`Puma` のバージョンも上げてあげる必要がありそう。
```console
$ bin/rails app:update
bin/rails aborted!
StandardError: Puma 5 is not compatible with Rack 3, please upgrade to Puma 6 or higher. (StandardError)
<internal:/home/kodama/.rbenv/versions/3.3.2/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
<internal:/home/kodama/.rbenv/versions/3.3.2/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
/home/kodama/work/ruby/ranguba/config/application.rb:25:in `<main>'
/home/kodama/work/ruby/ranguba/Rakefile:6:in `require_relative'
/home/kodama/work/ruby/ranguba/Rakefile:6:in `<main>'
bin/rails:4:in `<main>'
(See full trace by running task with --trace)
```

**Comment by otegami** [comment]
CI 上ではテストが通っているが、ローカルでコケているので今後のバージョンアップ作業のためにも調査する。

```console
$ bin/rails test
...
Error: test_query_string(SearchTest::ValidConditionTest):
  Selenium::WebDriver::Error::SessionNotCreatedError: session not created
  from unknown error: no chrome binary at /usr/bin/google-chrome
/home/kodama/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/selenium-webdriver-4.23.0/lib/selenium/webdriver/remote/response.rb:62:in `add_cause'
/home/kodama/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/selenium-webdriver-4.23.0/lib/selenium/webdriver/remote/response.rb:41:in `error'
/home/kodama/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/selenium-webdriver-4.23.0/lib/selenium/webdriver/remote/response.rb:52:in `assert_ok'
/home/kodama/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/selenium-webdriver-4.23.0/lib/selenium/webdriver/remote/response.rb:34:in `initialize'
/home/kodama/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/selenium-webdriver-4.23.0/lib/selenium/webdriver/remote/http/common.rb:101:in `new'
/home/kodama/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/selenium-webdriver-4.23.0/lib/selenium/webdriver/remote/http/common.rb:101:in `create_response'
/home/kodama/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/selenium-webdriver-4.23.0/lib/selenium/webdriver/remote/http/default.rb:103:in `request'
/home/kodama/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/selenium-webdriver-4.23.0/lib/selenium/webdriver/remote/http/common.rb:67:in `call'
/home/kodama/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/selenium-webdriver-4.23.0/lib/selenium/webdriver/remote/bridge.rb:675:in `execute'
/home/kodama/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/selenium-webdriver-4.23.0/lib/selenium/webdriver/remote/bridge.rb:76:in `create_session'
/home/kodama/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/selenium-webdriver-4.23.0/lib/selenium/webdriver/common/driver.rb:323:in `block in create_bridge'
<internal:kernel>:90:in `tap'
/home/kodama/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/selenium-webdriver-4.23.0/lib/selenium/webdriver/common/driver.rb:322:in `create_bridge'
/home/kodama/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/selenium-webdriver-4.23.0/lib/selenium/webdriver/common/driver.rb:73:in `initialize'
/home/kodama/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/selenium-webdriver-4.23.0/lib/selenium/webdriver/chrome/driver.rb:35:in `initialize'
/home/kodama/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/selenium-webdriver-4.23.0/lib/selenium/webdriver/common/driver.rb:47:in `new'
/home/kodama/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/selenium-webdriver-4.23.0/lib/selenium/webdriver/common/driver.rb:47:in `for'
/home/kodama/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/selenium-webdriver-4.23.0/lib/selenium/webdriver.rb:89:in `for'
/home/kodama/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/capybara-3.40.0/lib/capybara/selenium/driver.rb:75:in `browser'
/home/kodama/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/actionpack-7.1.3.4/lib/action_dispatch/system_testing/driver.rb:55:in `block in register_selenium'
<internal:kernel>:90:in `tap'
/home/kodama/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/actionpack-7.1.3.4/lib/action_dispatch/system_testing/driver.rb:54:in `register_selenium'
/home/kodama/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/actionpack-7.1.3.4/lib/action_dispatch/system_testing/driver.rb:41:in `block in register'
/home/kodama/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/capybara-3.40.0/lib/capybara/session.rb:106:in `driver'
/home/kodama/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/capybara-3.40.0/lib/capybara/session.rb:92:in `initialize'
/home/kodama/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/capybara-3.40.0/lib/capybara.rb:422:in `new'
/home/kodama/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/capybara-3.40.0/lib/capybara.rb:422:in `block in session_pool'
/home/kodama/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/capybara-3.40.0/lib/capybara.rb:317:in `[]'
/home/kodama/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/capybara-3.40.0/lib/capybara.rb:317:in `current_session'
/home/kodama/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/capybara-3.40.0/lib/capybara/dsl.rb:46:in `page'
/home/kodama/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/actionpack-7.1.3.4/lib/action_dispatch/system_testing/test_helpers/screenshot_helper.rb:106:in `save_image'
/home/kodama/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/actionpack-7.1.3.4/lib/action_dispatch/system_testing/test_helpers/screenshot_helper.rb:36:in `take_screenshot'
/home/kodama/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/actionpack-7.1.3.4/lib/action_dispatch/system_testing/test_helpers/screenshot_helper.rb:47:in `take_failed_screenshot'
/home/kodama/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/test-unit-rails-7.0.2/lib/test/unit/rails/test_help.rb:132:in `block in <class:SystemTestCase>'
===========================================================================================================================================
Finished in 32.477906876 seconds.
-------------------------------------------------------------------------------------------------------------------------------------------
88 tests, 307 assertions, 0 failures, 46 errors, 0 pendings, 0 omissions, 0 notifications
73.8636% passed
-------------------------------------------------------------------------------------------------------------------------------------------
2.71 tests/s, 9.45 assertions/s
```

---

Chrome binary は存在していそう。
```console
$ which google-chrome
/usr/bin/google-chrome
```
